require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, '15.1'

install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!


abstract_target 'USupportCommonPods' do
  use_expo_modules!

  # Link all React Native native modules (Stripe, gesture-handler, screens, etc.)
  # Without this, only Expo modules are linked and you get TurboModuleRegistry.getEnforcing(...) could not be found.
  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"]
  else
    config_command = [
      'node', '--no-warnings', '--eval', "require('expo/bin/autolinking')",
      'expo-modules-autolinking', 'react-native-config', '--json', '--platform', 'ios'
    ]
  end
  config = use_native_modules!(config_command)

  # Use Firebase 11.11.0 - RNFB uses FIROptions.trackingID/androidClientID/deepLinkURLScheme
  # which were removed in Firebase iOS SDK 12
  $FirebaseSDKVersion = '11.11.0'

  # React Native Firebase (keep explicit for version pinning)
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'
  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'Firebase', '11.11.0', :modular_headers => true
  pod 'FirebaseCore', '11.11.0', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  pod 'FirebaseCoreExtension', '11.11.0', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  target 'USupport' do
  end
  
  target 'USupportDev' do
  end
  

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # fmt 11.x + Apple Clang 16+: consteval in basic_format_string fails to compile.
    # base.h always #defines FMT_USE_CONSTEVAL after -D; wrap auto-detect in #ifndef FMT_USE_CONSTEVAL.
    fmt_base = File.join(installer.sandbox.root, 'fmt/include/fmt/base.h')
    if File.exist?(fmt_base)
      File.chmod(0o644, fmt_base)
      contents = File.read(fmt_base)
      unless contents.include?('[USupport] FMT_USE_CONSTEVAL wrap')
        contents.sub!(
          "// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\n" \
          "#if !defined(__cpp_lib_is_constant_evaluated)",
          "// Detect consteval, C++20 constexpr extensions and std::is_constant_evaluated.\n" \
          "// [USupport] FMT_USE_CONSTEVAL wrap for Apple Clang 16+ (see Podfile)\n" \
          "#ifndef FMT_USE_CONSTEVAL\n" \
          "#if !defined(__cpp_lib_is_constant_evaluated)"
        )
        contents.sub!(
          "#elif FMT_GCC_VERSION >= 1002 || FMT_CLANG_VERSION >= 1101\n" \
          "#  define FMT_USE_CONSTEVAL 1\n" \
          "#else\n" \
          "#  define FMT_USE_CONSTEVAL 0\n" \
          "#endif\n" \
          "#if FMT_USE_CONSTEVAL\n" \
          "#  define FMT_CONSTEVAL consteval",
          "#elif FMT_GCC_VERSION >= 1002 || FMT_CLANG_VERSION >= 1101\n" \
          "#  define FMT_USE_CONSTEVAL 1\n" \
          "#else\n" \
          "#  define FMT_USE_CONSTEVAL 0\n" \
          "#endif\n" \
          "#endif\n" \
          "#if FMT_USE_CONSTEVAL\n" \
          "#  define FMT_CONSTEVAL consteval"
        )
        File.write(fmt_base, contents)
      end
    end

    installer.pods_project.targets.each do |target|
      next unless target.name == 'fmt'
      target.build_configurations.each do |config|
        defs = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        defs = [defs] if defs.is_a?(String)
        defs = defs ? defs.dup : ['$(inherited)']
        defs << 'FMT_USE_CONSTEVAL=0' unless defs.any? { |d| d.to_s.include?('FMT_USE_CONSTEVAL') }
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
      end
    end

    bitcode_strip_path = `xcrun -sdk iphoneos --find bitcode_strip`.strip

     # Actual binary paths
    giphy_framework = 'Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64/GiphyUISDK.framework/GiphyUISDK'

    if File.exist?(giphy_framework)
      puts "Stripping bitcode from GiphyUISDK..."
      system("#{bitcode_strip_path} #{giphy_framework} -r -o #{giphy_framework}")
    else
      puts "Giphy binary not found at: #{giphy_framework}"
    end


    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
